const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const ROOT=process.cwd();
function rep(file,re,to,label){let s=fs.readFileSync(file,'utf8');if(!re.test(s))throw new Error('PATCH_MISS:'+label);s=s.replace(re,to);fs.writeFileSync(file,s)}
(async()=>{
 let b64=''; const base='https://raw.githubusercontent.com/byDenoso/AuditData/nexo-science-center-v2-visual-preview/nexo-science-center-v2-visual/part';
 for(let i=0;i<8;i++){const r=await fetch(base+String(i).padStart(4,'0')+'.txt');if(!r.ok)throw Error('SOURCE_FETCH:'+i);const t=(await r.text()).trim();b64+=t;console.log(JSON.stringify({part:i,status:'VERIFIED'}))}
 const raw=Buffer.from(b64,'base64'),sha=crypto.createHash('sha256').update(raw).digest('hex'); if(sha!=='2e0ada006f1375043fbee47668e2f42d1ae17a61dd9496b03ffb186aaeeccdb6')throw Error('SOURCE_SHA:'+sha);
 fs.writeFileSync('/tmp/v2.tgz',raw);fs.rmSync('/tmp/v2',{recursive:true,force:true});fs.mkdirSync('/tmp/v2');cp.execFileSync('tar',['-xzf','/tmp/v2.tgz','-C','/tmp/v2']);
 for(const n of ['src','scripts','tests','tsconfig.json','next.config.ts','next-env.d.ts']){fs.rmSync(path.join(ROOT,n),{recursive:true,force:true});fs.cpSync(path.join('/tmp/v2',n),path.join(ROOT,n),{recursive:true})}
 const rt=path.join(ROOT,'src/components/science-center/runtime.ts'),css=path.join(ROOT,'src/app/globals.css');
 const testFile=path.join(ROOT,'tests/v2-uiux-refocus.test.mjs');
 fs.writeFileSync(testFile,`import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';const r=fs.readFileSync('src/components/science-center/runtime.ts','utf8'),c=fs.readFileSync('src/app/globals.css','utf8');test('focus and race guard',()=>{assert.match(r,/focusedDomainId/);assert.match(r,/domainRequestSeq/);assert.match(r,/focusedDomainPositions/);assert.match(r,/requestSeq !== state\\.domainRequestSeq/)});test('legend filters',()=>{assert.match(r,/filter-domain-legend/);assert.match(r,/filter-evidence-legend/);assert.match(r,/Crítico/);assert.match(r,/Aprovados/);assert.match(c,/graph-filter-row/)});test('overflow containment',()=>{assert.match(r,/statusLabel\\(tone\\)/);assert.match(c,/grid-auto-columns:clamp\\(240px/);assert.match(c,/roadmap-step-footer \\.status-chip/)});`);
 let red=cp.spawnSync(process.execPath,['--test',testFile],{encoding:'utf8'});if(red.status===0)throw Error('RED_UNEXPECTED_PASS');console.log('UIUX_RED_CONFIRMED');
 rep(rt,/(lastGoodCockpit:\s*null)(\s*\n\s*};)/,`$1,\n      focusedDomainId: null, domainRequestSeq: 0, domainLegendFilter: 'all', evidenceLegendFilter: 'all'$2`,'state');
 rep(rt,/cacheElements\(\);\n\s*document\.addEventListener\('click'/,`cacheElements();\n      ensureGraphLegendControls();\n      document.addEventListener('click'`,'init');
 rep(rt,/else if \(action === 'filter-tests'\) setTestFilter\(trigger\.getAttribute\('data-status'\)\);/,`else if (action === 'filter-tests') setTestFilter(trigger.getAttribute('data-status'));\n      else if (action === 'filter-domain-legend') setDomainLegendFilter(trigger.getAttribute('data-status'));\n      else if (action === 'filter-evidence-legend') setEvidenceLegendFilter(trigger.getAttribute('data-status'));`,'click');
 rep(rt,/state\.domain = cockpit\.selected_domain;\n\s*state\.sourceTargets = Object\.create\(null\);/,`state.domain = cockpit.selected_domain;\n        state.focusedDomainId = state.domain && state.domain.id || null;\n        state.domainRequestSeq += 1;\n        state.sourceTargets = Object.create(null);`,'load-focus');
 const helpers=`    function ensureGraphLegendControls(){function row(kind,items){var r=el('div','graph-filter-row graph-filter-row--'+kind);appendTextElement(r,'span','Legenda','graph-filter-label');items.forEach(function(x){var b=document.createElement('button');b.type='button';b.setAttribute('data-action',kind==='domain'?'filter-domain-legend':'filter-evidence-legend');b.setAttribute('data-status',x[0]);b.setAttribute('aria-pressed',String(x[0]==='all'));b.textContent=x[1];if(x[0]==='all')b.classList.add('is-active');r.appendChild(b)});return r}var np=elements.domainGraphWrap&&elements.domainGraphWrap.closest('.network-panel');if(np&&!np.querySelector('.graph-filter-row--domain'))np.querySelector('.panel-header').after(row('domain',[['all','Todos'],['critical','Crítico'],['attention','Atenção'],['active','Ativo'],['healthy','Saudável'],['unknown','Sem cobertura']]));var ep=elements.evidenceGraph&&elements.evidenceGraph.closest('.evidence-panel');if(ep&&!ep.querySelector('.graph-filter-row--evidence'))ep.querySelector('.panel-header').after(row('evidence',[['all','Todos'],['passed','Aprovados'],['conflict','Conflitos'],['running','Executando'],['decision','Decisões'],['evidence','Evidências']]))}\n    function syncLegend(action,value){document.querySelectorAll('[data-action="'+action+'"]').forEach(function(b){var a=b.getAttribute('data-status')===value;b.classList.toggle('is-active',a);b.setAttribute('aria-pressed',String(a))})}\n    function setDomainLegendFilter(v){state.domainLegendFilter=v||'all';syncLegend('filter-domain-legend',state.domainLegendFilter);renderDomainNetwork()}\n    function setEvidenceLegendFilter(v){state.evidenceLegendFilter=v||'all';syncLegend('filter-evidence-legend',state.evidenceLegendFilter);if(state.domain)renderEvidenceGraph(state.domain)}\n    function evidenceLegendMatch(n){var f=state.evidenceLegendFilter||'all';if(f==='all')return true;if(f==='decision'||f==='evidence')return n.kind===f;return n.kind==='test'&&safeStatus(n.state)===f}\n`;
 rep(rt,/\s+async function selectDomain\(domainId\) \{/,`\n${helpers}    async function selectDomain(domainId) {`,'helpers');
 rep(rt,/async function selectDomain\(domainId\) \{[\s\S]*?function renderAll\(\) \{/m,`async function selectDomain(domainId) {\n      if (!domainId || state.loading) return;\n      if (state.domain && state.domain.id === domainId && state.focusedDomainId === domainId) return;\n      var requestSeq = ++state.domainRequestSeq; state.focusedDomainId = domainId; markDomainSelected(domainId); renderDomainNetwork(); setDomainBusy(true);\n      try { var nextDomain = await rpc('nscGetDomain', domainId); if (requestSeq !== state.domainRequestSeq) return; state.domain = nextDomain; if(state.cockpit){state.cockpit.selected_domain_id=domainId;state.cockpit.selected_domain=state.domain} renderDomainDetail();renderDomainNetwork();renderDomainSelector();renderDomainRail();document.querySelector('.domain-section').scrollIntoView({behavior:prefersReducedMotion()?'auto':'smooth',block:'start'}); }\n      catch(error){if(requestSeq===state.domainRequestSeq)toast('Domínio indisponível: '+(error.message||error),'error')} finally{if(requestSeq===state.domainRequestSeq)setDomainBusy(false)}\n    }\n    function renderAll() {`,'select');
 rep(rt,/var positions = radialPositions\(domains, 480, 255, 300, 175\);\n\s*var edgesLayer = svgEl\('g'\);[\s\S]*?var relations = domainRelations\(domains\);\n\s*var selectedDomainId = state\.domain && state\.domain\.id;/,`var relations = domainRelations(domains);\n      var selectedDomainId = state.focusedDomainId || (state.domain && state.domain.id);\n      var positions = focusedDomainPositions(domains, relations, selectedDomainId, 480, 255);\n      var edgesLayer = svgEl('g');\n      edgesLayer.setAttribute('aria-hidden','true');\n      var nodesLayer = svgEl('g');`,'network-head');
 rep(rt,/if \(selectedDomainId && relation\.source !== selectedDomainId && relation\.target !== selectedDomainId\) line\.classList\.add\('is-dimmed'\);/,`if (selectedDomainId && relation.source !== selectedDomainId && relation.target !== selectedDomainId) line.classList.add('is-dimmed'); else if(selectedDomainId) line.classList.add('is-focus-edge');`,'edge-focus');
 rep(rt,/if \(state\.domain && state\.domain\.id === domain\.id\) group\.classList\.add\('is-selected'\);\n\s*if \(dimmed\) group\.classList\.add\('is-dimmed'\);/,`var focusedDomainId=state.focusedDomainId||(state.domain&&state.domain.id); if(focusedDomainId===domain.id)group.classList.add('is-selected'); if(dimmed)group.classList.add('is-dimmed'); if(state.domainLegendFilter!=='all'&&safeStatus(domain.status)!==state.domainLegendFilter&&focusedDomainId!==domain.id)group.classList.add('is-legend-muted');`,'node-focus');
 const pos=`    function focusedDomainPositions(domains,relations,id,cx,cy){if(!id||!domains.some(function(d){return d.id===id}))return radialPositions(domains,cx,cy,300,175);var p=Object.create(null);p[id]={x:cx,y:cy};var rel=Object.create(null);relations.forEach(function(e){if(e.source===id)rel[e.target]=true;if(e.target===id)rel[e.source]=true});var inner=domains.filter(function(d){return d.id!==id&&rel[d.id]}),outer=domains.filter(function(d){return d.id!==id&&!rel[d.id]});inner.forEach(function(d,i){var a=-Math.PI/2+2*Math.PI*i/Math.max(1,inner.length);p[d.id]={x:cx+Math.cos(a)*225,y:cy+Math.sin(a)*132}});outer.forEach(function(d,i){var a=-Math.PI/2+2*Math.PI*i/Math.max(1,outer.length);p[d.id]={x:cx+Math.cos(a)*355,y:cy+Math.sin(a)*205}});return p}\n`;
 rep(rt,/    function radialPositions\(items, centerX, centerY, radiusX, radiusY\) \{/,pos+`    function radialPositions(items, centerX, centerY, radiusX, radiusY) {`,'positions');
 rep(rt,/var line = svgEl\('line', 'evidence-edge relation--' \+ safeClass\(edge\.relation\)\);/,`var line = svgEl('line','evidence-edge relation--'+safeClass(edge.relation)); if(edge.source===graph.nodes[0].id||edge.target===graph.nodes[0].id)line.classList.add('is-focus-link');`,'e-edge');
 rep(rt,/nodesLayer\.appendChild\(createEvidenceNode\(node, positions\[node\.id\], index\)\);/,`var ne=createEvidenceNode(node,positions[node.id],index); if(!evidenceLegendMatch(node)&&node.kind!=='domain')ne.classList.add('is-legend-muted'); nodesLayer.appendChild(ne);`,'e-node');
 rep(rt,/footer\.appendChild\(chip\(item\.stage === null \|\| item\.stage === undefined \? item\.state \|\| 'OPEN' : 'Stage ' \+ item\.stage, 'status-chip status--' \+ tone\)\);/,`var roadmapChip=chip(item.stage===null||item.stage===undefined?statusLabel(tone):'Stage '+item.stage,'status-chip status--'+tone);roadmapChip.title=String(item.state||'OPEN').replace(/_/g,' ');footer.appendChild(roadmapChip);`,'roadmap');
 rep(rt,/function setDomainBusy\(busy\) \{\n\s*document\.querySelectorAll\('\[data-action="select-domain"\]'\)\.forEach\(function \(button\) \{ button\.setAttribute\('aria-busy', String\(busy\)\); \}\);\n\s*\}/,`function setDomainBusy(busy){document.querySelectorAll('[data-action="select-domain"]').forEach(function(button){button.setAttribute('aria-busy',String(busy&&button.getAttribute('data-domain-id')===state.focusedDomainId))});var w=document.querySelector('.domain-workspace');if(w)w.classList.toggle('is-refocusing',Boolean(busy))}`,'busy');
 fs.appendFileSync(css,`\n/* V2.1 focus and legend */\n.graph-filter-row{display:flex;gap:5px;align-items:center;padding:7px 14px;border-block:1px solid rgba(23,49,76,.55);overflow-x:auto;background:rgba(5,18,32,.56)}.graph-filter-label{color:var(--subtle);font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.graph-filter-row button{flex:0 0 auto;min-height:25px;padding:0 9px;border:1px solid var(--line);border-radius:999px;color:var(--muted);background:rgba(7,22,39,.6);font-size:8px;cursor:pointer}.graph-filter-row button.is-active,.graph-filter-row button:hover{color:#e6f9ff;border-color:var(--cyan);background:var(--cyan-soft)}.graph-edge.is-focus-edge{stroke:var(--cyan);stroke-width:2.35;opacity:.95}.graph-edge.is-dimmed{opacity:.1}.graph-node.is-dimmed{opacity:.2}.graph-node.is-legend-muted,.evidence-node.is-legend-muted{opacity:.1}.graph-node.is-selected .node-ring{stroke-width:3.3}.evidence-edge.is-focus-link{stroke:var(--cyan);stroke-width:1.9;opacity:.9}.domain-workspace.is-refocusing .evidence-panel{opacity:.72}.domain-workspace .evidence-panel{transition:opacity .16s ease}.roadmap-track{grid-auto-columns:clamp(240px,34vw,290px);scroll-snap-type:x proximity}.roadmap-step{display:flex;flex-direction:column;min-height:270px;padding:40px 14px 14px;overflow:hidden;scroll-snap-align:start}.roadmap-step h3{line-height:1.35;-webkit-line-clamp:3}.roadmap-action{-webkit-line-clamp:4}.roadmap-criterion{-webkit-line-clamp:3}.roadmap-step-footer{margin-top:auto;min-width:0;flex-wrap:wrap}.roadmap-step-footer .status-chip{max-width:calc(100% - 66px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.compact-item h4{padding-right:0;line-height:1.35;-webkit-line-clamp:3}.compact-item p{-webkit-line-clamp:3}.compact-item .status-chip,.compact-item .priority-chip{position:static;display:inline-flex;width:max-content;max-width:100%;margin-top:8px}.domain-evidence-grid{align-items:start}.evidence-panel{align-self:start}@media(max-width:720px){.graph-filter-row{padding-inline:10px}.roadmap-track{grid-auto-columns:minmax(235px,82vw)}.roadmap-step{min-height:250px}}\n`);
 const green=cp.spawnSync(process.execPath,['--test',testFile],{encoding:'utf8'});process.stdout.write(green.stdout||'');process.stderr.write(green.stderr||'');if(green.status!==0)throw Error('GREEN_FAILED');console.log('UIUX_GREEN_CONFIRMED');console.log(JSON.stringify({status:'SOURCE_READY_V2_1_UIUX',archiveSha256:sha}));
})();